/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DiagnosticsServer;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;

public class Server {

    public static void main(String[] args) {
        String reading = "";
        try (
                ServerSocket serverSocket = new ServerSocket(4444);
                Socket clientSocket = serverSocket.accept();
                PrintWriter out = new PrintWriter(clientSocket.getOutputStream(),true);
                BufferedReader in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()))
        ){
            System.out.println("Waiting");
            while (!reading.equals("exit")) {
                reading = in.readLine();
                out.println(reading.equals("exit") ? "Bye" : reading);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
