package InfrastructureManager.ModuleManagement.Exception.Execution;

/**
 * Signals that a certain {@link InfrastructureManager.ModuleManagement.PlatformModule} could not be found
 * in the list of configured modules. Normally, generated by naming errors.
 *
 * Not to be confused with {@link InfrastructureManager.ModuleManagement.Exception.Creation.ModuleNotDefinedException}
 * which is a "Configure-time" exception, that is thrown when an invalid module type or non defined module tries to
 * be configured. On the other hand, this exception signals a similar error but in run-time, after the modules were already
 * correctly configured.
 */
public class ModuleNotFoundException extends ModuleExecutionException {
    public ModuleNotFoundException(String message) {
        super(message);
    }
}
