name: Automatic Testing - Gradle

#The action will be triggered everytime a pull request is made that includes files in the src directory (master branch)
on: 
  pull_request:
    branches: 
      - master
    paths:
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 ##Copies the repository files in the remote machine
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1 #Sets up the Java version (8)
      with:
        java-version: 1.12
    - name: Cache Gradle packages #Saves gradles dependencies after a succesful run, so they dont have to be downloaded again, if there are changes in the build script skips the cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Open port 10500 for testing
      run: sudo ufw allow 10500
    - name: Test with Gradle ##Only testing with Gradle (Not building)
      run: ./gradlew test
